name: Deploy to Cloudflare

on:
  pull_request:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install
  
    - name: Run Build
      uses: borales/actions-yarn@v4
      with:
        cmd: build
      env:
        BASE_URL: ${{ secrets.BASE_URL }}